function filter(evt, column) {
	// Declare variables
	var input, filter, table, tr, td, i, txtValue;
	input = evt.target;
	filter = input.value.toUpperCase();
	table = evt.path[4];
	tr = table.getElementsByTagName("tr");

	// Loop through all table rows, and hide those who don't match the search query
	for (i = 2; i < tr.length; i++) {
		td = tr[i].getElementsByTagName("td")[column];
		if (td) {
			txtValue = td.textContent || td.innerText;
			if (txtValue.toUpperCase().indexOf(filter) > -1) {
				tr[i].style.display = "";
			} else {
				tr[i].style.display = "none";
			}
		}
	}
}

function goToMap(layer, featureID){
	var feature = layer._layers[featureID];
	if (feature.feature.geometry.type == 'Point' ) {
		map.setView(feature.getLatLng(), 16);
	} else {
		map.fitBounds(feature.getBounds());
	}

	document.getElementById('mapBtn').click();
	feature.openPopup();

	if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
		layer.bringToFront();
	};
}

tableHTML__Anguia_Preliminar_Oficiar_Wgs84 = '<table id="_Anguia_Preliminar_Oficiar_Wgs84_table">';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<tr>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Mapa</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Area_ha</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Cod_suelo</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Desc_pendi</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Desc_suelo</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Drenaje</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Fertilid_n</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Mater_orga</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>OBJECTID</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Origen</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Pedregosid</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Pendiente</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Perfil</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Permeabili</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Profund_ef</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Shape_Area</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Shape_Leng</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Textura</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>Zona_vida</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>fid</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>pH</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>p_smpp_peG</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<th>p_smpp_per</th>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'</tr>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<tr>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 1)" placeholder="Procurar Area_ha"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 2)" placeholder="Procurar Cod_suelo"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 3)" placeholder="Procurar Desc_pendi"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 4)" placeholder="Procurar Desc_suelo"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 5)" placeholder="Procurar Drenaje"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 6)" placeholder="Procurar Fertilid_n"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 7)" placeholder="Procurar Mater_orga"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 8)" placeholder="Procurar OBJECTID"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 9)" placeholder="Procurar Origen"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 10)" placeholder="Procurar Pedregosid"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 11)" placeholder="Procurar Pendiente"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 12)" placeholder="Procurar Perfil"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 13)" placeholder="Procurar Permeabili"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 14)" placeholder="Procurar Profund_ef"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 15)" placeholder="Procurar Shape_Area"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 16)" placeholder="Procurar Shape_Leng"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 17)" placeholder="Procurar Textura"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 18)" placeholder="Procurar Zona_vida"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 19)" placeholder="Procurar fid"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 20)" placeholder="Procurar pH"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 21)" placeholder="Procurar p_smpp_peG"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 22)" placeholder="Procurar p_smpp_per"></td>';
tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'</tr>';

var _Anguia_Preliminar_Oficiar_Wgs84_IDs = Object.keys(_Anguia_Preliminar_Oficiar_Wgs84._layers);
for (var i=0; i < _Anguia_Preliminar_Oficiar_Wgs84_IDs.length; i++){
	var feature = _Anguia_Preliminar_Oficiar_Wgs84._layers[_Anguia_Preliminar_Oficiar_Wgs84_IDs[i]].feature;
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += '<tr>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td onclick="goToMap(_Anguia_Preliminar_Oficiar_Wgs84, ' + _Anguia_Preliminar_Oficiar_Wgs84_IDs[i] + ')"><img src="javascript/icon.png" width="32px" height="32px"/></td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Area_ha'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Cod_suelo'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Desc_pendi'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Desc_suelo'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Drenaje'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Fertilid_n'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Mater_orga'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['OBJECTID'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Origen'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Pedregosid'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Pendiente'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Perfil'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Permeabili'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Profund_ef'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Shape_Area'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Shape_Leng'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Textura'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['Zona_vida'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['fid'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['pH'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['p_smpp_peG'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += 	'<td>' + feature.properties['p_smpp_per'] + '</td>';
	tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += '</tr>';
}

tableHTML__Anguia_Preliminar_Oficiar_Wgs84 += '</table>';
document.getElementById('_Anguia_Preliminar_Oficiar_Wgs84_tab').innerHTML = tableHTML__Anguia_Preliminar_Oficiar_Wgs84;

tableHTML__Santos_Tomas_1_Oficiar_Wgs84 = '<table id="_Santos_Tomas_1_Oficiar_Wgs84_table">';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<tr>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Mapa</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Area_ha</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Cod_suelo</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Desc_pendi</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Desc_suelo</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Drenaje</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Fertilid_n</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Mater_orga</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>OBJECTID</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Origen</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Pedregosid</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Pendiente</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Perfil</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Permeabili</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Profund_ef</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Shape_Area</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Shape_Leng</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Textura</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>Zona_vida</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>fid</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>pH</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>p_smpp_peG</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<th>p_smpp_per</th>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'</tr>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<tr>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 1)" placeholder="Procurar Area_ha"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 2)" placeholder="Procurar Cod_suelo"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 3)" placeholder="Procurar Desc_pendi"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 4)" placeholder="Procurar Desc_suelo"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 5)" placeholder="Procurar Drenaje"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 6)" placeholder="Procurar Fertilid_n"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 7)" placeholder="Procurar Mater_orga"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 8)" placeholder="Procurar OBJECTID"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 9)" placeholder="Procurar Origen"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 10)" placeholder="Procurar Pedregosid"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 11)" placeholder="Procurar Pendiente"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 12)" placeholder="Procurar Perfil"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 13)" placeholder="Procurar Permeabili"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 14)" placeholder="Procurar Profund_ef"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 15)" placeholder="Procurar Shape_Area"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 16)" placeholder="Procurar Shape_Leng"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 17)" placeholder="Procurar Textura"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 18)" placeholder="Procurar Zona_vida"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 19)" placeholder="Procurar fid"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 20)" placeholder="Procurar pH"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 21)" placeholder="Procurar p_smpp_peG"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 22)" placeholder="Procurar p_smpp_per"></td>';
tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'</tr>';

var _Santos_Tomas_1_Oficiar_Wgs84_IDs = Object.keys(_Santos_Tomas_1_Oficiar_Wgs84._layers);
for (var i=0; i < _Santos_Tomas_1_Oficiar_Wgs84_IDs.length; i++){
	var feature = _Santos_Tomas_1_Oficiar_Wgs84._layers[_Santos_Tomas_1_Oficiar_Wgs84_IDs[i]].feature;
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += '<tr>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td onclick="goToMap(_Santos_Tomas_1_Oficiar_Wgs84, ' + _Santos_Tomas_1_Oficiar_Wgs84_IDs[i] + ')"><img src="javascript/icon.png" width="32px" height="32px"/></td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Area_ha'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Cod_suelo'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Desc_pendi'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Desc_suelo'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Drenaje'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Fertilid_n'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Mater_orga'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['OBJECTID'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Origen'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Pedregosid'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Pendiente'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Perfil'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Permeabili'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Profund_ef'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Shape_Area'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Shape_Leng'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Textura'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['Zona_vida'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['fid'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['pH'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['p_smpp_peG'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += 	'<td>' + feature.properties['p_smpp_per'] + '</td>';
	tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += '</tr>';
}

tableHTML__Santos_Tomas_1_Oficiar_Wgs84 += '</table>';
document.getElementById('_Santos_Tomas_1_Oficiar_Wgs84_tab').innerHTML = tableHTML__Santos_Tomas_1_Oficiar_Wgs84;

tableHTML__UT_CALLAYUC = '<table id="_UT_CALLAYUC_table">';
tableHTML__UT_CALLAYUC += 	'<tr>';
tableHTML__UT_CALLAYUC += 		'<th>Mapa</th>';
tableHTML__UT_CALLAYUC += 		'<th>Area_ha</th>';
tableHTML__UT_CALLAYUC += 		'<th>Cod_suelo</th>';
tableHTML__UT_CALLAYUC += 		'<th>Desc_pendi</th>';
tableHTML__UT_CALLAYUC += 		'<th>Desc_suelo</th>';
tableHTML__UT_CALLAYUC += 		'<th>Drenaje</th>';
tableHTML__UT_CALLAYUC += 		'<th>Fertilid_n</th>';
tableHTML__UT_CALLAYUC += 		'<th>Mater_orga</th>';
tableHTML__UT_CALLAYUC += 		'<th>OBJECTID</th>';
tableHTML__UT_CALLAYUC += 		'<th>Origen</th>';
tableHTML__UT_CALLAYUC += 		'<th>Pedregosid</th>';
tableHTML__UT_CALLAYUC += 		'<th>Pendiente</th>';
tableHTML__UT_CALLAYUC += 		'<th>Perfil</th>';
tableHTML__UT_CALLAYUC += 		'<th>Permeabili</th>';
tableHTML__UT_CALLAYUC += 		'<th>Profund_ef</th>';
tableHTML__UT_CALLAYUC += 		'<th>Shape_Area</th>';
tableHTML__UT_CALLAYUC += 		'<th>Shape_Leng</th>';
tableHTML__UT_CALLAYUC += 		'<th>Textura</th>';
tableHTML__UT_CALLAYUC += 		'<th>Zona_vida</th>';
tableHTML__UT_CALLAYUC += 		'<th>fid</th>';
tableHTML__UT_CALLAYUC += 		'<th>pH</th>';
tableHTML__UT_CALLAYUC += 		'<th>p_smpp_peG</th>';
tableHTML__UT_CALLAYUC += 		'<th>p_smpp_per</th>';
tableHTML__UT_CALLAYUC += 	'</tr>';
tableHTML__UT_CALLAYUC += 	'<tr>';
tableHTML__UT_CALLAYUC += 		'<td></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 1)" placeholder="Procurar Area_ha"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 2)" placeholder="Procurar Cod_suelo"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 3)" placeholder="Procurar Desc_pendi"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 4)" placeholder="Procurar Desc_suelo"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 5)" placeholder="Procurar Drenaje"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 6)" placeholder="Procurar Fertilid_n"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 7)" placeholder="Procurar Mater_orga"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 8)" placeholder="Procurar OBJECTID"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 9)" placeholder="Procurar Origen"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 10)" placeholder="Procurar Pedregosid"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 11)" placeholder="Procurar Pendiente"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 12)" placeholder="Procurar Perfil"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 13)" placeholder="Procurar Permeabili"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 14)" placeholder="Procurar Profund_ef"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 15)" placeholder="Procurar Shape_Area"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 16)" placeholder="Procurar Shape_Leng"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 17)" placeholder="Procurar Textura"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 18)" placeholder="Procurar Zona_vida"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 19)" placeholder="Procurar fid"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 20)" placeholder="Procurar pH"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 21)" placeholder="Procurar p_smpp_peG"></td>';
tableHTML__UT_CALLAYUC += 		'<td><input type="text" onkeyup="filter(event, 22)" placeholder="Procurar p_smpp_per"></td>';
tableHTML__UT_CALLAYUC += 	'</tr>';

var _UT_CALLAYUC_IDs = Object.keys(_UT_CALLAYUC._layers);
for (var i=0; i < _UT_CALLAYUC_IDs.length; i++){
	var feature = _UT_CALLAYUC._layers[_UT_CALLAYUC_IDs[i]].feature;
	tableHTML__UT_CALLAYUC += '<tr>';
	tableHTML__UT_CALLAYUC += 	'<td onclick="goToMap(_UT_CALLAYUC, ' + _UT_CALLAYUC_IDs[i] + ')"><img src="javascript/icon.png" width="32px" height="32px"/></td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Area_ha'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Cod_suelo'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Desc_pendi'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Desc_suelo'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Drenaje'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Fertilid_n'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Mater_orga'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['OBJECTID'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Origen'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Pedregosid'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Pendiente'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Perfil'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Permeabili'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Profund_ef'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Shape_Area'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Shape_Leng'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Textura'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['Zona_vida'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['fid'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['pH'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['p_smpp_peG'] + '</td>';
	tableHTML__UT_CALLAYUC += 	'<td>' + feature.properties['p_smpp_per'] + '</td>';
	tableHTML__UT_CALLAYUC += '</tr>';
}

tableHTML__UT_CALLAYUC += '</table>';
document.getElementById('_UT_CALLAYUC_tab').innerHTML = tableHTML__UT_CALLAYUC;

tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 = '<table id="_UT_SanJuanCutervo_Oficiar_Wgs84_table">';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<tr>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Mapa</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Area_ha</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Cod_suelo</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Desc_pendi</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Desc_suelo</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Drenaje</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Fertilid_n</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Mater_orga</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>OBJECTID</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Origen</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Pedregosid</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Pendiente</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Perfil</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Permeabili</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Profund_ef</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Shape_Area</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Shape_Leng</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Textura</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>Zona_vida</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>fid</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>pH</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>p_smpp_peG</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<th>p_smpp_per</th>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'</tr>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<tr>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 1)" placeholder="Procurar Area_ha"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 2)" placeholder="Procurar Cod_suelo"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 3)" placeholder="Procurar Desc_pendi"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 4)" placeholder="Procurar Desc_suelo"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 5)" placeholder="Procurar Drenaje"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 6)" placeholder="Procurar Fertilid_n"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 7)" placeholder="Procurar Mater_orga"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 8)" placeholder="Procurar OBJECTID"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 9)" placeholder="Procurar Origen"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 10)" placeholder="Procurar Pedregosid"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 11)" placeholder="Procurar Pendiente"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 12)" placeholder="Procurar Perfil"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 13)" placeholder="Procurar Permeabili"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 14)" placeholder="Procurar Profund_ef"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 15)" placeholder="Procurar Shape_Area"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 16)" placeholder="Procurar Shape_Leng"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 17)" placeholder="Procurar Textura"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 18)" placeholder="Procurar Zona_vida"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 19)" placeholder="Procurar fid"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 20)" placeholder="Procurar pH"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 21)" placeholder="Procurar p_smpp_peG"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 		'<td><input type="text" onkeyup="filter(event, 22)" placeholder="Procurar p_smpp_per"></td>';
tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'</tr>';

var _UT_SanJuanCutervo_Oficiar_Wgs84_IDs = Object.keys(_UT_SanJuanCutervo_Oficiar_Wgs84._layers);
for (var i=0; i < _UT_SanJuanCutervo_Oficiar_Wgs84_IDs.length; i++){
	var feature = _UT_SanJuanCutervo_Oficiar_Wgs84._layers[_UT_SanJuanCutervo_Oficiar_Wgs84_IDs[i]].feature;
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += '<tr>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td onclick="goToMap(_UT_SanJuanCutervo_Oficiar_Wgs84, ' + _UT_SanJuanCutervo_Oficiar_Wgs84_IDs[i] + ')"><img src="javascript/icon.png" width="32px" height="32px"/></td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Area_ha'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Cod_suelo'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Desc_pendi'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Desc_suelo'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Drenaje'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Fertilid_n'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Mater_orga'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['OBJECTID'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Origen'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Pedregosid'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Pendiente'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Perfil'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Permeabili'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Profund_ef'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Shape_Area'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Shape_Leng'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Textura'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['Zona_vida'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['fid'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['pH'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['p_smpp_peG'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += 	'<td>' + feature.properties['p_smpp_per'] + '</td>';
	tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += '</tr>';
}

tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84 += '</table>';
document.getElementById('_UT_SanJuanCutervo_Oficiar_Wgs84_tab').innerHTML = tableHTML__UT_SanJuanCutervo_Oficiar_Wgs84;

tableHTML__UT_TORIBIO_CASANOVA_1 = '<table id="_UT_TORIBIO_CASANOVA_1_table">';
tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<tr>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Mapa</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Area_ha</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Cod_suelo</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Desc_pendi</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Desc_suelo</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Drenaje</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Fertilid_n</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Mater_orga</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>OBJECTID</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Origen</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Pedregosid</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Pendiente</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Perfil</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Permeabili</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Profund_ef</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Shape_Area</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Shape_Leng</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Textura</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>Zona_vida</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>fid</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>pH</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>p_smpp_peG</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<th>p_smpp_per</th>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 	'</tr>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<tr>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 1)" placeholder="Procurar Area_ha"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 2)" placeholder="Procurar Cod_suelo"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 3)" placeholder="Procurar Desc_pendi"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 4)" placeholder="Procurar Desc_suelo"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 5)" placeholder="Procurar Drenaje"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 6)" placeholder="Procurar Fertilid_n"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 7)" placeholder="Procurar Mater_orga"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 8)" placeholder="Procurar OBJECTID"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 9)" placeholder="Procurar Origen"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 10)" placeholder="Procurar Pedregosid"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 11)" placeholder="Procurar Pendiente"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 12)" placeholder="Procurar Perfil"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 13)" placeholder="Procurar Permeabili"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 14)" placeholder="Procurar Profund_ef"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 15)" placeholder="Procurar Shape_Area"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 16)" placeholder="Procurar Shape_Leng"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 17)" placeholder="Procurar Textura"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 18)" placeholder="Procurar Zona_vida"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 19)" placeholder="Procurar fid"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 20)" placeholder="Procurar pH"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 21)" placeholder="Procurar p_smpp_peG"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 		'<td><input type="text" onkeyup="filter(event, 22)" placeholder="Procurar p_smpp_per"></td>';
tableHTML__UT_TORIBIO_CASANOVA_1 += 	'</tr>';

var _UT_TORIBIO_CASANOVA_1_IDs = Object.keys(_UT_TORIBIO_CASANOVA_1._layers);
for (var i=0; i < _UT_TORIBIO_CASANOVA_1_IDs.length; i++){
	var feature = _UT_TORIBIO_CASANOVA_1._layers[_UT_TORIBIO_CASANOVA_1_IDs[i]].feature;
	tableHTML__UT_TORIBIO_CASANOVA_1 += '<tr>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td onclick="goToMap(_UT_TORIBIO_CASANOVA_1, ' + _UT_TORIBIO_CASANOVA_1_IDs[i] + ')"><img src="javascript/icon.png" width="32px" height="32px"/></td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Area_ha'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Cod_suelo'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Desc_pendi'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Desc_suelo'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Drenaje'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Fertilid_n'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Mater_orga'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['OBJECTID'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Origen'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Pedregosid'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Pendiente'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Perfil'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Permeabili'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Profund_ef'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Shape_Area'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Shape_Leng'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Textura'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['Zona_vida'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['fid'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['pH'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['p_smpp_peG'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += 	'<td>' + feature.properties['p_smpp_per'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_1 += '</tr>';
}

tableHTML__UT_TORIBIO_CASANOVA_1 += '</table>';
document.getElementById('_UT_TORIBIO_CASANOVA_1_tab').innerHTML = tableHTML__UT_TORIBIO_CASANOVA_1;

tableHTML__UT_TORIBIO_CASANOVA_2 = '<table id="_UT_TORIBIO_CASANOVA_2_table">';
tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<tr>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Mapa</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Area_ha</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Cod_suelo</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Desc_pendi</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Desc_suelo</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Drenaje</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Fertilid_n</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Mater_orga</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>OBJECTID</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Origen</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Pedregosid</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Pendiente</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Perfil</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Permeabili</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Profund_ef</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Shape_Area</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Shape_Leng</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Textura</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>Zona_vida</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>fid</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>pH</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>p_smpp_peG</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<th>p_smpp_per</th>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 	'</tr>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<tr>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 1)" placeholder="Procurar Area_ha"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 2)" placeholder="Procurar Cod_suelo"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 3)" placeholder="Procurar Desc_pendi"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 4)" placeholder="Procurar Desc_suelo"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 5)" placeholder="Procurar Drenaje"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 6)" placeholder="Procurar Fertilid_n"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 7)" placeholder="Procurar Mater_orga"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 8)" placeholder="Procurar OBJECTID"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 9)" placeholder="Procurar Origen"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 10)" placeholder="Procurar Pedregosid"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 11)" placeholder="Procurar Pendiente"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 12)" placeholder="Procurar Perfil"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 13)" placeholder="Procurar Permeabili"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 14)" placeholder="Procurar Profund_ef"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 15)" placeholder="Procurar Shape_Area"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 16)" placeholder="Procurar Shape_Leng"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 17)" placeholder="Procurar Textura"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 18)" placeholder="Procurar Zona_vida"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 19)" placeholder="Procurar fid"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 20)" placeholder="Procurar pH"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 21)" placeholder="Procurar p_smpp_peG"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 		'<td><input type="text" onkeyup="filter(event, 22)" placeholder="Procurar p_smpp_per"></td>';
tableHTML__UT_TORIBIO_CASANOVA_2 += 	'</tr>';

var _UT_TORIBIO_CASANOVA_2_IDs = Object.keys(_UT_TORIBIO_CASANOVA_2._layers);
for (var i=0; i < _UT_TORIBIO_CASANOVA_2_IDs.length; i++){
	var feature = _UT_TORIBIO_CASANOVA_2._layers[_UT_TORIBIO_CASANOVA_2_IDs[i]].feature;
	tableHTML__UT_TORIBIO_CASANOVA_2 += '<tr>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td onclick="goToMap(_UT_TORIBIO_CASANOVA_2, ' + _UT_TORIBIO_CASANOVA_2_IDs[i] + ')"><img src="javascript/icon.png" width="32px" height="32px"/></td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Area_ha'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Cod_suelo'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Desc_pendi'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Desc_suelo'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Drenaje'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Fertilid_n'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Mater_orga'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['OBJECTID'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Origen'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Pedregosid'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Pendiente'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Perfil'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Permeabili'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Profund_ef'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Shape_Area'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Shape_Leng'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Textura'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['Zona_vida'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['fid'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['pH'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['p_smpp_peG'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += 	'<td>' + feature.properties['p_smpp_per'] + '</td>';
	tableHTML__UT_TORIBIO_CASANOVA_2 += '</tr>';
}

tableHTML__UT_TORIBIO_CASANOVA_2 += '</table>';
document.getElementById('_UT_TORIBIO_CASANOVA_2_tab').innerHTML = tableHTML__UT_TORIBIO_CASANOVA_2;

